name: Run tests
on:
    workflow_dispatch:
    push:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - run: npm i
            - run: tsc
            - run: npm run ci
